# Generated by Django 4.0.4 on 2022-05-07 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_min', models.CharField(max_length=255)),
                ('slug_min', models.SlugField(max_length=255, unique=True)),
                ('body_min', models.TextField()),
                ('created_min', models.DateTimeField(auto_now_add=True)),
                ('updated_min', models.DateTimeField(auto_now=True)),
                ('author_min', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostIot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_iot', models.CharField(max_length=255)),
                ('slug_iot', models.SlugField(max_length=255, unique=True)),
                ('body_iot', models.TextField()),
                ('created_iot', models.DateTimeField(auto_now_add=True)),
                ('updated_iot', models.DateTimeField(auto_now=True)),
                ('author_iot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostGa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ga', models.CharField(max_length=255)),
                ('slug_ga', models.SlugField(max_length=255, unique=True)),
                ('body_ga', models.TextField()),
                ('created_ga', models.DateTimeField(auto_now_add=True)),
                ('updated_ga', models.DateTimeField(auto_now=True)),
                ('author_ga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
