# Generated by Django 4.0.4 on 2022-05-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_alter_postga_author_ga_alter_postga_body_ga_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postga',
            old_name='slug_ga',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='postiot',
            old_name='slug_iot',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='postmin',
            old_name='slug_min',
            new_name='slug',
        ),
    ]
