# Generated by Django 4.0.4 on 2022-05-08 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_rename_slug_ga_postga_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postga',
            old_name='author_ga',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='postga',
            old_name='body_ga',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='postga',
            old_name='created_ga',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='postga',
            old_name='title_ga',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='postga',
            old_name='updated_ga',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='postiot',
            old_name='author_iot',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='postiot',
            old_name='body_iot',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='postiot',
            old_name='created_iot',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='postiot',
            old_name='title_iot',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='postiot',
            old_name='updated_iot',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='postmin',
            old_name='author_min',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='postmin',
            old_name='body_min',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='postmin',
            old_name='created_min',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='postmin',
            old_name='title_min',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='postmin',
            old_name='updated_min',
            new_name='updated',
        ),
    ]
