# Generated by Django 4.0.4 on 2022-05-28 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmin',
            options={'ordering': ('-created',)},
        ),
    ]
