# Generated by Django 4.0.4 on 2022-05-30 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogga', '0002_remove_answerga_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerga',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answersga', to='blogga.postga', verbose_name='Dúvida'),
        ),
    ]
